# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRooms
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de negócios",
    "description": "Sala para falar sobre negócios"
}

###

@roomId = {{createRooms.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create questions
# @name createQuestions
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "Como funcionam as parábolas"
}